site_name: Ragas
repo_name: explodinggradients/ragas
repo_url: https://github.com/explodinggradients/ragas
watch:
  - src

# Navigation
nav:
  - "": index.md
  - 🚀 Get Started:
      - getstarted/index.md
      - Installation: getstarted/install.md
      - Evaluate Using Metrics: getstarted/rag_evaluation.md
      - Generate Synthetic Testset for RAG: getstarted/rag_testset_generation.md
  - 📚 Core Concepts:
      - concepts/index.md
      - Components:
          - concepts/components/index.md
          - concepts/components/prompt.md
          - concepts/components/eval_sample.md
          - concepts/components/eval_dataset.md
      - Metrics:
          - concepts/metrics/index.md
          - Overview: concepts/metrics/overview/index.md
          - Available Metrics: 
            - concepts/metrics/available_metrics/index.md
            - Retrieval Augmented Generation:
              - Context Precision: concepts/metrics/available_metrics/context_precision.md
              - Context Recall: concepts/metrics/available_metrics/context_recall.md
              - Context Entities Recall: concepts/metrics/available_metrics/context_entities_recall.md
              - Noise Sensitivity: concepts/metrics/available_metrics/noise_sensitivity.md
              - Response Relevancy: concepts/metrics/available_metrics/answer_relevance.md
              - Faithfulness: concepts/metrics/available_metrics/faithfulness.md
            - Agents or Tool Use Cases:
                - Topic Adherence: concepts/metrics/available_metrics/topic_adherence.md
                - Tool Call Accuracy: concepts/metrics/available_metrics/agents/#tool-call-accuracy
                - Agent Goal Accuracy: concepts/metrics/available_metrics/agents/#agent-goal-accuracy
            - Natural Language Comparison:
                - Factual Correctness: concepts/metrics/available_metrics/factual_correctness.md
                - Semantic Similarity: concepts/metrics/available_metrics/semantic_similarity.md
                - Non LLM String Similarity: concepts/metrics/available_metrics/traditional/#non-llm-string-similarity
                - BLEU Score: concepts/metrics/available_metrics/traditional/#bleu-score
                - ROUGE Score: concepts/metrics/available_metrics/traditional/#rouge-score
                - String Presence: concepts/metrics/available_metrics/traditional/#string-presence
                - Exact Match: concepts/metrics/available_metrics/traditional/#exact-match
            - SQL:
                - Execution based Datacompy Score: concepts/metrics/available_metrics/sql/#execution-based-metrics
                - SQL Query Equivalence: concepts/metrics/available_metrics/sql/#sql-query-semantic-equivalence
            - General Purpose:
                - Aspect Critic: concepts/metrics/available_metrics/general_purpose/#aspect-critic
                - Simple Criteria Scoring: concepts/metrics/available_metrics/general_purpose/#simple-criteria-scoring
                - Rubrics Based Scoring: concepts/metrics/available_metrics/general_purpose/#rubrics-based-scoring
                - Instance Specific Rubrics Scoring: concepts/metrics/available_metrics/general_purpose/#instance-specific-rubrics-scoring
            - Other Tasks:
                - Summarization: concepts/metrics/available_metrics/summarization_score.md
      - Test Data Generation:
          - concepts/test_data_generation/index.md
          - RAG:
              - concepts/test_data_generation/rag.md
              - KG Building: concepts/test_data_generation/rag/#knowledge-graph-creation
              - Scenario Generation: concepts/test_data_generation/rag/#scenario-generation
          - Agents or tool use:
              - concepts/test_data_generation/agents.md
      - Feedback Intelligence:
          - concepts/feedback/index.md
  - 🛠️ How-to Guides:
      - howtos/index.md
      - Customizations:
          - howtos/customizations/index.md
          - General:
            - Customise models: howtos/customizations/customize_models.md
            - Run Config: howtos/customizations/run_config.ipynb
          - Metrics:
            - Modify Prompts: howtos/customizations/metrics/modifying-prompts-metrics.ipynb
            - Add Custom Metrics: howtos/customizations/metrics/write_your_own_metric.ipynb
          - Testset Generation:
            - Add custom scenarios: howtos/customizations/testset_generation/add_custom_scenarios.md
            - Seed Generation with Production Data: howtos/customizations/testset_generation/seed_generation_with_production_data.md
      - Applications:
          - howtos/applications/index.md
      - Integrations:
          - howtos/integrations/index.md
  - 📖 References: references/
  - ❤️ Community: community/index.md

# Material-Docs Theme
theme:
  name: material
  logo: _static/imgs/ragas-logo.png
  favicon: _static/favicon.ico
  palette:
    scheme: slate
    primary: custom
    accent: white
  features:
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.indexes
    - navigation.footer
    - search.suggest
    - search.highlight
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets:
      base_path: ['./docs/extra/components/']

# Extra CSS
extra_css:
  - extra/style.css

# Plugins
extra:
  version:
    provider: mike
    alias: true
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
plugins:
  - search
  - git-revision-date-localized:
      enabled: !ENV [MKDOCS_CI, false]
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [MKDOCS_CI, false]
      repository: explodinggradients/ragas
      branch: main
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
  - mkdocs-jupyter:
      execute: false
      include: ["*.ipynb"]
      ignore: ["*.md"]
      jupyter_options:
        hide_input: false
        hide_output: false
        code_folding: true
        code_line_numbers: true
        jupyter_images: true
        jupyter_table_beautifier: true
  - glightbox
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index

extra_javascript:
  - _static/js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
